import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./src/generated/prisma/client";
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const p = new PrismaClient({ adapter });
const users = await p.user.findMany({ select: { id: true, email: true } });
const products = await p.product.findMany({ select: { id: true, name: true, userId: true } });
const scored = await p.scoredPost.count();
const signals = await p.signal.count();
const sources = await p.source.count({ where: { selected: true } });
console.log(JSON.stringify({ users, products, scored, signals, sources }, null, 1));
await p.$disconnect();
