import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal/legal-page-shell";
import { MONITORED_CHANNEL_NAMES, formatChannelList } from "@/lib/channels";

export const metadata: Metadata = {
  title: "Terms of Service — Getrive",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" updated="July 19, 2026">
      <p>
        Getrive (&ldquo;Getrive,&rdquo; &ldquo;we,&rdquo; or &ldquo;us&rdquo;) is currently operated
        by an individual founder, not yet through a registered company. These Terms govern your use
        of the Getrive application. By creating an account, you agree to them.
      </p>

      <h2>What Getrive does</h2>
      <p>
        Getrive helps founders find posts — on {formatChannelList(MONITORED_CHANNEL_NAMES)} — that
        describe the pain point their product solves, and drafts a suggested reply using AI. <strong>Getrive
        never posts, comments, DMs, or sends anything on your behalf.</strong> Every draft is something you
        review, edit, and send yourself, under your own
        account on that platform, subject to that platform&apos;s own rules and terms.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>
          You&apos;re responsible for keeping your account secure — your password if you sign in
          with email, or your Google account if you sign in with Google.
        </li>
        <li>You must provide accurate information when creating an account and describing your product.</li>
        <li>You&apos;re responsible for the content of anything you choose to post or send — Getrive only drafts suggestions.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use Getrive to spam, harass, or mislead people on {formatChannelList([...MONITORED_CHANNEL_NAMES, "elsewhere"], "or")}.</li>
        <li>Attempt to circumvent usage limits (e.g. monitored-source caps, polling rate limits, daily AI-scoring caps) built into the product.</li>
        <li>Use the tracking snippet or redirect mechanism to collect visitor data you don&apos;t have a legitimate right to collect (see the Privacy Policy for what you&apos;re responsible for there).</li>
        <li>Reverse-engineer, scrape, or resell access to the service.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Reply drafts, positioning statements, channel/subreddit suggestions,
        and relevance scores are generated by third-party AI models (see the Privacy Policy for which
        ones) and may be inaccurate, irrelevant, or inappropriate for a given context. You&apos;re
        responsible for reviewing anything before you send or post it publicly under your own name.
      </p>

      <h2>Service availability</h2>
      <p>
        Getrive is an early-access product. Features, limits, and pricing may change, and the
        service is provided without uptime guarantees. Each monitored platform&apos;s own access
        policies ({formatChannelList(MONITORED_CHANNEL_NAMES)}, and any others we add) — which
        Getrive doesn&apos;t control — can also affect whether signal ingestion works at any given
        time.
      </p>

      <h2>No warranty; limitation of liability</h2>
      <p>
        Getrive is provided &ldquo;as is,&rdquo; without warranties of any kind. To the fullest
        extent permitted by law, Getrive isn&apos;t liable for indirect, incidental, or consequential
        damages arising from your use of the service, including anything you post to Reddit based on
        a suggested draft.
      </p>

      <h2>Termination</h2>
      <p>
        You can stop using Getrive and delete your account at any time. We may suspend or terminate
        accounts that violate these Terms.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these Terms as the product evolves. Material changes will be reflected by
        updating the date at the top of this page.
      </p>

      <h2>Governing law</h2>
      <p>
        These Terms are governed by the laws of the founder&apos;s home jurisdiction, to be specified
        here once formalized with legal counsel.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms:{" "}
        <a href="mailto:senkcsani@gmail.com">senkcsani@gmail.com</a>
      </p>
    </LegalPageShell>
  );
}
